@extends('errors.layout')
@section('code', '403')
@section('icon', 'fa-solid fa-lock')
@section('heading', 'Acceso denegado')
@section('message', 'No tienes permiso para ver esta página o recurso. Si crees que es un error, contacta al administrador.')