@extends('errors.layout')
@section('code', '404')
@section('icon', 'fa-solid fa-map-signs')
@section('heading', 'Página no encontrada')
@section('message', 'La página que buscas no existe o fue movida.')