@extends('errors.layout')
@section('code', '419')
@section('icon', 'fa-solid fa-clock-rotate-left')
@section('heading', 'Sesión expirada')
@section('message', 'Tu sesión expiró por seguridad. Recarga la página e inténtalo de nuevo.')