@extends('errors.layout')
@section('code', '500')
@section('icon', 'fa-solid fa-triangle-exclamation')
@section('heading', 'Error del servidor')
@section('message', 'Algo salió mal de nuestro lado. Intenta de nuevo en un momento.')